PlainSqlSlickPostgreSubject: 1000 exceptions with message Failure(org.postgresql.util.PSQLException: ERROR: relation "slick_account" does not exist
  Position: 8) (of class scala.util.Failure)
scala.MatchError: Failure(org.postgresql.util.PSQLException: ERROR: relation "slick_account" does not exist
  Position: 8) (of class scala.util.Failure)
	at databench.slick.PlainSqlSlickPostgreSubject.withTransactionRetry(PlainSqlSlickPostgreSubject.scala:41)
	at databench.slick.PlainSqlSlickPostgreSubject.transfer(PlainSqlSlickPostgreSubject.scala:60)
	at databench.slick.PlainSqlSlickPostgreSubject.transfer(PlainSqlSlickPostgreSubject.scala:22)
	at databench.task.TransferTask.perform(TransferTask.scala:15)
	at databench.task.TransferTask.perform(TransferTask.scala:8)
	at databench.runner.TurnVMThread$$anonfun$responses$1$$anonfun$apply$1.apply(TurnVM.scala:40)
	at databench.runner.TurnVMThread$$anonfun$responses$1$$anonfun$apply$1.apply(TurnVM.scala:40)
	at scala.util.Try$.apply(Try.scala:161)
	at databench.runner.TurnVMThread$$anonfun$responses$1.apply(TurnVM.scala:40)
	at databench.runner.TurnVMThread$$anonfun$responses$1.apply(TurnVM.scala:39)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1156)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at databench.runner.TurnVMThread.responses$lzycompute(TurnVM.scala:39)
	at databench.runner.TurnVMThread.responses(TurnVM.scala:38)
	at databench.runner.TurnVMThread.run(TurnVM.scala:44)
PlainSqlSlickPostgreSubject: 1000 exceptions with message Failure(org.postgresql.util.PSQLException: ERROR: relation "slick_account" does not exist
  Position: 8) (of class scala.util.Failure)
scala.MatchError: Failure(org.postgresql.util.PSQLException: ERROR: relation "slick_account" does not exist
  Position: 8) (of class scala.util.Failure)
	at databench.slick.PlainSqlSlickPostgreSubject.withTransactionRetry(PlainSqlSlickPostgreSubject.scala:41)
	at databench.slick.PlainSqlSlickPostgreSubject.transfer(PlainSqlSlickPostgreSubject.scala:60)
	at databench.slick.PlainSqlSlickPostgreSubject.transfer(PlainSqlSlickPostgreSubject.scala:22)
	at databench.task.TransferTask.perform(TransferTask.scala:15)
	at databench.task.TransferTask.perform(TransferTask.scala:8)
	at databench.runner.TurnVMThread$$anonfun$responses$1$$anonfun$apply$1.apply(TurnVM.scala:40)
	at databench.runner.TurnVMThread$$anonfun$responses$1$$anonfun$apply$1.apply(TurnVM.scala:40)
	at scala.util.Try$.apply(Try.scala:161)
	at databench.runner.TurnVMThread$$anonfun$responses$1.apply(TurnVM.scala:40)
	at databench.runner.TurnVMThread$$anonfun$responses$1.apply(TurnVM.scala:39)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1156)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at databench.runner.TurnVMThread.responses$lzycompute(TurnVM.scala:39)
	at databench.runner.TurnVMThread.responses(TurnVM.scala:38)
	at databench.runner.TurnVMThread.run(TurnVM.scala:44)
